### ISSUE TITLE
Could not open library 'libaubio.4.2.2.dylib'

### ISSUE THREAD

**Issue by Mestelan** [repl-electric/sonic-pi.el#26]
Hello,

This is a fresh install on Debian 9.8 (Stretch). 

(Steps taken:
```
git clone git@github.com:samaaron/sonic-pi.git
cd sonic-pi && ./app/server/ruby/bin/compile-extensions.rb
git clone git@github.com:repl-electric/sonic-pi.el.git ~/.sonic-pi.el
```
etc...)

`sonic-pi-jack-in` displays this error in sonic-pi-server-messages:
```
/media/data/code/git_repos/music-making/sonic-pi/app/server/ruby/vendor/ffi-1.9.17/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library 'libaubio.4.2.2.dylib': libaubio.4.2.2.dylib: cannot open shared object file: No such file or directory. (LoadError)
Could not open library 'libaubio.4.2.2.dylib.so': libaubio.4.2.2.dylib.so: cannot open shared object file: No such file or directory.
Could not open library 'libaubio.so.1': libaubio.so.1: cannot open shared object file: No such file or directory.
Could not open library 'libaubio.so.5': libaubio.so.5: cannot open shared object file: No such file or directory.
Could not open library 'aubio1.dll': aubio1.dll: cannot open shared object file: No such file or directory.
Could not open library 'libaubio1.dll.so': libaubio1.dll.so: cannot open shared object file: No such file or directory
	from /media/data/code/git_repos/music-making/sonic-pi/app/server/ruby/vendor/ffi-1.9.17/lib/ffi/library.rb:100:in `map'
	from /media/data/code/git_repos/music-making/sonic-pi/app/server/ruby/vendor/ffi-1.9.17/lib/ffi/library.rb:100:in `ffi_lib'
	from /media/data/code/git_repos/music-making/sonic-pi/app/server/ruby/vendor/ruby-aubio-prerelease/lib/aubio/api.rb:9:in `<module:Api>'
	from /media/data/code/git_repos/music-making/sonic-pi/app/server/ruby/vendor/ruby-aubio-prerelease/lib/aubio/api.rb:4:in `<module:Aubio>'
	from /media/data/code/git_repos/music-making/sonic-pi/app/server/ruby/vendor/ruby-aubio-prerelease/lib/aubio/api.rb:3:in `<top (required)>'
	from /media/data/code/git_repos/music-making/sonic-pi/app/server/ruby/vendor/ruby-aubio-prerelease/lib/aubio.rb:2:in `require_relative'
	from /media/data/code/git_repos/music-making/sonic-pi/app/server/ruby/vendor/ruby-aubio-prerelease/lib/aubio.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /media/data/code/git_repos/music-making/sonic-pi/app/server/ruby/lib/sonicpi/samplebuffer.rb:17:in `<top (required)>'
	from /media/data/code/git_repos/music-making/sonic-pi/app/server/ruby/lib/sonicpi/studio.rb:16:in `require_relative'
	from /media/data/code/git_repos/music-making/sonic-pi/app/server/ruby/lib/sonicpi/studio.rb:16:in `<top (required)>'
	from /home/jb/git_repos/music-making/sonic-pi/app/server/ruby/bin/sonic-pi-server.rb:20:in `require_relative'
	from /home/jb/git_repos/music-making/sonic-pi/app/server/ruby/bin/sonic-pi-server.rb:20:in `<main>'

Process sonic-pi-server exited abnormally with code 1

```

Here are the files present in `/usr/lib/x86_64-linux-gnu`

```
find /usr/lib/x86_64-linux-gnu -iname '*libaudio*'
/usr/lib/x86_64-linux-gnu/vlc/plugins/spu/libaudiobargraph_v_plugin.so
/usr/lib/x86_64-linux-gnu/vlc/plugins/audio_filter/libaudio_format_plugin.so
/usr/lib/x86_64-linux-gnu/vlc/plugins/audio_filter/libaudiobargraph_a_plugin.so
/usr/lib/x86_64-linux-gnu/vlc/plugins/misc/libaudioscrobbler_plugin.so
/usr/lib/x86_64-linux-gnu/libaudio.so.2
/usr/lib/x86_64-linux-gnu/libaudio.so.2.4
/usr/lib/x86_64-linux-gnu/libaudiofile.so.1.0.0
/usr/lib/x86_64-linux-gnu/libaudiofile.so.1
```
Am I missing something?

**Comment by Mestelan** [comment]
The error disappeared when I recompiled sonic-pi from scratch. 
Sorry about the noise (!).
